spring:
  application:
    name: feedify-backend
  datasource:
    driver-class-name: org.postgresql.Driver
    username: feedify-backend
    password: password
    url: jdbc:postgresql://localhost:5432/feedify
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  jackson:
    property-naming-strategy: SNAKE_CASE
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

common:
  version: 0.1
  env: dev
  public-domain: https://example.com
  content:
    storage:
    max-size: 83886080
    max-attachments: 10

jwt:
  secret:
  expiration: 2592000