name: feedify-backend CI/CD

on:
  push:
    branches:
      - main
      - dev

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: Run checkstyle tests
        run: ./gradlew checkstyleMain checkstyleTest

      - name: Upload checkstyle report
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-report
          path: build/reports/checkstyle/

      - name: Run unit tests
        run: ./gradlew test